### ISSUE TITLE
Use formation energies instead of reaction delta gs

### ISSUE THREAD

**Issue by teddygroves** [biosustain/Maud#194]
This should let us avoid free energy loops and more or less directly use numbers from equilibrator

**Comment by Midnighter** [comment]
Just a note that Elad really recommends not doing this because you will likely overestimate the uncertainties. We can chat about this next week if you like.

**Comment by LarsKeldNielsen** [comment]
Moritz

This is only true if you ignore the error-covariance matrix and work with variance only.

When Elad calculates dGr in eQuilibrator, he accounts for covariance by ignoring groups and components that do not change in the reaction. If you use dGf without the error covariance, the uncertainty explode since both the substrates and products will have the added noise of unchanging components. However, if you include error-covariance in all your calculations or samplings using dGf, the estimates end up the same.

Imagine a reaction converting a 4-group compound into another 4-group compound with 3 groups shared: [G1-G2-G3-G4] -> [G1-G2-G3-G5]. Let’s assume (conveniently if incorrect) that group values are estimate independently and look at the errors

V{dGf_substrate} = V{G1} + V{G2} + V{G3} + V{G4}
V{dGf_product} = V{G1} + V{G2} + V{G3} + V{G5}
COV(dGf_substrate, dGf_product) = V{G1} + V{G2} + V{G3}

dGf_reaction  = dGf_product - dGf_substrate
V{dGf_reaction} = V{dGf_substrate} + V{dGf_product} – 2 COV(dGf_substrate, dGf_product) = V{G4} + V{G5}

This is exactly the same value produced by equilibrator.

This is the point of the software that Vishnu has developed. The value of using dGf is that if you sample dGr independently, you end up with non-zero dG for loops.

Lars

**Comment by Midnighter** [comment]
> This is the point of the software that Vishnu has developed. The value of using dGf is that if you sample dGr independently, you end up with non-zero dG for loops.

I only read Teddy's short note above. I wasn't aware whether or not you are applying the same concept here in Maud so I left the note. Glad to hear that this is so :+1:
