### ISSUE TITLE
ImportError: cannot import name 'methionine' from 'maud.data.example_inputs' (unknown location)

### ISSUE THREAD

**Issue by janisshin** [biosustain/Maud#429]
Hello, I got the following error after following the instructions listed in the readme. 

``` python
> maud --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\miniconda3\envs\maud\Scripts\maud.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\miniconda3\envs\maud\Lib\site-packages\maud\cli.py", line 27, in <module>
    from maud.data.example_inputs import linear, methionine
ImportError: cannot import name 'methionine' from 'maud.data.example_inputs' (unknown location)
```
I'm not seeing the specified folder in my file explorer. Is this issue due to the lack of c++ toolchain?
![image](https://github.com/biosustain/Maud/assets/49432660/56af71f4-31f5-4237-9b25-469855154271)

**Comment by teddygroves** [comment]
Thanks a lot for the bug report! 

I think this error was caused by missing __init__.py files in the [example input folders](https://github.com/biosustain/Maud/tree/master/maud/data/example_inputs) leading to them not being added to the package. In other words it’s a bug not a sign that you need to install anything.
